version: '1.0'
services:
  mongodb:
    build: mongoDB
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongoDB:/data/db

  flask:
    build: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:
  mongoDB: